// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v5.26.1
// source: proto/fx/v1/fx.proto

package fxv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	FXService_GetRates_FullMethodName         = "/fx.v1.FXService/GetRates"
	FXService_CreateQuote_FullMethodName      = "/fx.v1.FXService/CreateQuote"
	FXService_CreateConversion_FullMethodName = "/fx.v1.FXService/CreateConversion"
	FXService_GetConversion_FullMethodName    = "/fx.v1.FXService/GetConversion"
)

// FXServiceClient is the client API for FXService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FXServiceClient interface {
	GetRates(ctx context.Context, in *GetRatesRequest, opts ...grpc.CallOption) (*GetRatesResponse, error)
	CreateQuote(ctx context.Context, in *CreateQuoteRequest, opts ...grpc.CallOption) (*Quote, error)
	CreateConversion(ctx context.Context, in *CreateConversionRequest, opts ...grpc.CallOption) (*Conversion, error)
	GetConversion(ctx context.Context, in *GetConversionRequest, opts ...grpc.CallOption) (*Conversion, error)
}

type fXServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewFXServiceClient(cc grpc.ClientConnInterface) FXServiceClient {
	return &fXServiceClient{cc}
}

func (c *fXServiceClient) GetRates(ctx context.Context, in *GetRatesRequest, opts ...grpc.CallOption) (*GetRatesResponse, error) {
	out := new(GetRatesResponse)
	err := c.cc.Invoke(ctx, FXService_GetRates_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fXServiceClient) CreateQuote(ctx context.Context, in *CreateQuoteRequest, opts ...grpc.CallOption) (*Quote, error) {
	out := new(Quote)
	err := c.cc.Invoke(ctx, FXService_CreateQuote_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fXServiceClient) CreateConversion(ctx context.Context, in *CreateConversionRequest, opts ...grpc.CallOption) (*Conversion, error) {
	out := new(Conversion)
	err := c.cc.Invoke(ctx, FXService_CreateConversion_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fXServiceClient) GetConversion(ctx context.Context, in *GetConversionRequest, opts ...grpc.CallOption) (*Conversion, error) {
	out := new(Conversion)
	err := c.cc.Invoke(ctx, FXService_GetConversion_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FXServiceServer is the server API for FXService service.
// All implementations must embed UnimplementedFXServiceServer
// for forward compatibility
type FXServiceServer interface {
	GetRates(context.Context, *GetRatesRequest) (*GetRatesResponse, error)
	CreateQuote(context.Context, *CreateQuoteRequest) (*Quote, error)
	CreateConversion(context.Context, *CreateConversionRequest) (*Conversion, error)
	GetConversion(context.Context, *GetConversionRequest) (*Conversion, error)
	mustEmbedUnimplementedFXServiceServer()
}

// UnimplementedFXServiceServer must be embedded to have forward compatible implementations.
type UnimplementedFXServiceServer struct {
}

func (UnimplementedFXServiceServer) GetRates(context.Context, *GetRatesRequest) (*GetRatesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRates not implemented")
}
func (UnimplementedFXServiceServer) CreateQuote(context.Context, *CreateQuoteRequest) (*Quote, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateQuote not implemented")
}
func (UnimplementedFXServiceServer) CreateConversion(context.Context, *CreateConversionRequest) (*Conversion, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateConversion not implemented")
}
func (UnimplementedFXServiceServer) GetConversion(context.Context, *GetConversionRequest) (*Conversion, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetConversion not implemented")
}
func (UnimplementedFXServiceServer) mustEmbedUnimplementedFXServiceServer() {}

// UnsafeFXServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FXServiceServer will
// result in compilation errors.
type UnsafeFXServiceServer interface {
	mustEmbedUnimplementedFXServiceServer()
}

func RegisterFXServiceServer(s grpc.ServiceRegistrar, srv FXServiceServer) {
	s.RegisterService(&FXService_ServiceDesc, srv)
}

func _FXService_GetRates_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRatesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FXServiceServer).GetRates(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FXService_GetRates_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FXServiceServer).GetRates(ctx, req.(*GetRatesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FXService_CreateQuote_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateQuoteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FXServiceServer).CreateQuote(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FXService_CreateQuote_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FXServiceServer).CreateQuote(ctx, req.(*CreateQuoteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FXService_CreateConversion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateConversionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FXServiceServer).CreateConversion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FXService_CreateConversion_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FXServiceServer).CreateConversion(ctx, req.(*CreateConversionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FXService_GetConversion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetConversionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FXServiceServer).GetConversion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FXService_GetConversion_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FXServiceServer).GetConversion(ctx, req.(*GetConversionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// FXService_ServiceDesc is the grpc.ServiceDesc for FXService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FXService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "fx.v1.FXService",
	HandlerType: (*FXServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetRates",
			Handler:    _FXService_GetRates_Handler,
		},
		{
			MethodName: "CreateQuote",
			Handler:    _FXService_CreateQuote_Handler,
		},
		{
			MethodName: "CreateConversion",
			Handler:    _FXService_CreateConversion_Handler,
		},
		{
			MethodName: "GetConversion",
			Handler:    _FXService_GetConversion_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/fx/v1/fx.proto",
}
